language: node_js
node_js: "node"

sudo: required
dist: trusty

before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install memcached
 - sudo echo "127.0.0.1    url-cache" >> /etc/hosts

install:
 - npm install

script:
 - npm start &
 - sleep 10
 - npm test