language: node_js
node_js: "node"

sudo: required

before_install:
 - sudo apt-get -y update
 - sudo apt-get -y install memcached

install:
 - npm install

script:
 - npm start &
 - sleep 10
 - npm test